### ISSUE TITLE
turn off LED when stopping a recording?

### ISSUE THREAD

**Issue by dprotter** [open-ephys/Bonsai.Miniscope#16]
Ive just started playing with this package, so let me know if there is a more appropriate place to ask questions. 

I'm wondering if there is a way to set the LED to 0 when I stop the bonsai recording? Its not a big deal to stop the recording, then restart and manually set the LED power, but it would be nice to have it potentially be automatic. 

Thanks!

**Comment by jonnew** [comment]
This is a desirable enough behavior that I updated the package to do it without any workflow logic. `Bonsai.Miniscope` version 1.4.1 should be available in the package manager momentarily. Test it out when you have the chance and let me know if it solves this issue.

**Comment by jonnew** [comment]
I have not heard a reply. I'm closing this.
